"use client";

import { useEffect, useMemo, useState } from "react";

type Fund = { id:string; name:string; latestNav:number|null; finalDailyScore:number; actionTag:string; weightedSectorMove:number; strategicScore:number; navOpportunityScore:number; proxyIndex:string; reason:string };
type Payload = { generatedAt:string; marketRegime:any; strongestIndices:any[]; weakestIndices:any[]; sectorHeatmap:any[]; indexDashboard:any[]; funds:Fund[]; topFunds:Fund[]; tacticalAllocation:any[]; sourceStatus?:any };

const pct=(n:number|null|undefined)=>n==null?"—":`${n>=0?"+":""}${n.toFixed(2)}%`;
const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
const actionColor=(a:string)=>a.includes("BUY")?"border-emerald-500/30 bg-emerald-500/15 text-emerald-300":a==="ACCUMULATE"?"border-cyan-500/30 bg-cyan-500/15 text-cyan-300":a==="AVOID TODAY"?"border-red-500/30 bg-red-500/15 text-red-300":a==="WAIT"?"border-amber-500/30 bg-amber-500/15 text-amber-300":"border-slate-500/20 bg-slate-500/10 text-slate-300";

function Stat({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="text-[10px] uppercase tracking-[.18em] text-slate-500">{label}</div><div className="mt-2 text-xl font-semibold text-white">{value}</div>{sub&&<div className="mt-1 text-xs text-slate-400">{sub}</div>}</div>}

export default function TerminalDashboard(){
 const [data,setData]=useState<Payload|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("ALL"); const [last,setLast]=useState<Date|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/dashboard",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error||"Dashboard API failed");setData(j.payload??j);setLast(new Date());}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard");}finally{setLoading(false);}};
 useEffect(()=>{void load();const id=setInterval(()=>void load(),900000);return()=>clearInterval(id)},[]);
 const funds=useMemo(()=>data?.funds?.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())&&(filter==="ALL"||f.actionTag===filter))??[],[data,query,filter]);
 if(loading&&!data)return <main className="min-h-screen bg-[#070b12] text-white grid place-items-center"><div className="text-sm text-slate-400">Loading Smart MF Terminal…</div></main>;
 if(!data)return <main className="min-h-screen bg-[#070b12] text-white grid place-items-center"><div className="text-center"><div className="text-lg">Unable to load dashboard.</div><div className="mt-2 text-xs text-slate-500">{error||"Try Refresh."}</div><button onClick={load} className="mt-4 rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Retry</button></div></main>;
 const breadth=data.marketRegime?.breadthPercent??0; const best=data.topFunds?.[0];
 return <main className="min-h-screen bg-[#070b12] text-slate-200"><div className="mx-auto max-w-[1600px] px-5 py-6 lg:px-8">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3"><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/><h1 className="text-xl font-bold text-white">SMART MF TERMINAL</h1><span className="rounded-full border border-cyan-400/20 bg-cyan-400/10 px-2 py-1 text-[10px] font-semibold tracking-widest text-cyan-300">LIVE ENGINE</span></div><p className="mt-1 text-xs text-slate-500">Sector-aware mutual fund opportunity intelligence · No database required</p></div><div className="flex items-center gap-3"><span className="text-xs text-slate-500">{last?`Updated ${last.toLocaleTimeString()}`:"Updating…"}</span><button onClick={load} disabled={loading} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-xs hover:bg-white/10">↻ Refresh</button></div></header>
  {error&&<div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs text-amber-300">{error}</div>}
  <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat label="Market Regime" value={data.marketRegime?.badge??"—"} sub={data.marketRegime?.strategyNote}/><Stat label="Market Breadth" value={`${breadth.toFixed(0)}%`} sub="tracked indices positive"/><Stat label="Top Opportunity" value={best?.name?.split(" Fund")[0]??"—"} sub={best?`${best.finalDailyScore.toFixed(0)} score · ${best.actionTag}`:"—"}/><Stat label="Strongest Index" value={data.strongestIndices?.[0]?.name?.replace("NIFTY ","")??"—"} sub={pct(data.strongestIndices?.[0]?.changePercent)}/><Stat label="Weakest Index" value={data.weakestIndices?.[0]?.name?.replace("NIFTY ","")??"—"} sub={pct(data.weakestIndices?.[0]?.changePercent)}/></section>
  <div className="mt-6 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Today’s Opportunity Radar</h2><p className="mt-1 text-xs text-slate-500">Trend + NAV history + weighted sector weakness</p></div><div className="text-xs text-slate-500">{data.funds?.length??0} funds</div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-white/10 text-[10px] uppercase tracking-widest text-slate-500"><th className="pb-3">Fund</th><th className="pb-3">Action</th><th className="pb-3">Score</th><th className="pb-3">Sector Move</th><th className="pb-3">Trend</th><th className="pb-3">Opportunity</th></tr></thead><tbody>{funds.slice(0,12).map(f=><tr key={f.id} className="border-b border-white/5"><td className="py-3 pr-4"><div className="font-medium text-white">{f.name}</div><div className="mt-1 text-[10px] text-slate-500">{f.proxyIndex}</div></td><td><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold ${actionColor(f.actionTag)}`}>{f.actionTag}</span></td><td className="font-bold text-white">{f.finalDailyScore.toFixed(0)}</td><td className={f.weightedSectorMove<0?"text-emerald-300":"text-slate-300"}>{pct(f.weightedSectorMove)}</td><td className="text-slate-300">{f.strategicScore.toFixed(0)}</td><td className="text-slate-300">{f.navOpportunityScore.toFixed(0)}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl border border-white/10 bg-gradient-to-br from-cyan-500/[.10] to-white/[.025] p-5"><h2 className="font-semibold text-white">Tactical Allocation</h2><p className="mt-1 text-xs text-slate-500">Optional configured top-up</p><div className="mt-5 space-y-4">{data.tacticalAllocation?.length?data.tacticalAllocation.map((x:any)=><div key={x.fundId}><div className="flex justify-between text-xs"><span>{x.fundName}</span><b>{x.weightPercent.toFixed(1)}%</b></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-400" style={{width:`${x.weightPercent}%`}}/></div><div className="mt-1 text-[11px] text-cyan-300">{money(x.amount)}</div></div>):<div className="rounded-xl border border-dashed border-white/10 p-6 text-center text-xs text-slate-500">No tactical top-up configured.</div>}</div></section></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold text-white">Sector Heatmap</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{data.sectorHeatmap.map((s:any)=><div key={s.name} className={`rounded-xl border p-3 ${s.changePercent<0?"border-red-500/15 bg-red-500/[.07]":"border-emerald-500/15 bg-emerald-500/[.06]"}`}><div className="text-[10px] text-slate-500">{s.name.replace("NIFTY ","")}</div><div className={`mt-1 text-lg font-semibold ${s.changePercent<0?"text-red-300":"text-emerald-300"}`}>{pct(s.changePercent)}</div></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><h2 className="font-semibold text-white">Index Trend Matrix</h2><div className="mt-4 max-h-[320px] overflow-auto"><table className="w-full text-xs"><thead className="text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="pb-2 text-left">Index</th><th className="pb-2 text-right">Today</th><th className="pb-2 text-right">1M</th><th className="pb-2 text-right">Trend</th></tr></thead><tbody>{data.indexDashboard.map((x:any)=><tr key={x.name} className="border-t border-white/5"><td className="py-2">{x.name}</td><td className={`py-2 text-right ${x.today<0?"text-red-300":"text-emerald-300"}`}>{pct(x.today)}</td><td className="py-2 text-right text-slate-400">{pct(x.oneMonth)}</td><td className="py-2 text-right">{x.trend}</td></tr>)}</tbody></table></div></section></div>
  <section className="mt-5 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold text-white">All Fund Signals</h2><p className="mt-1 text-xs text-slate-500">Research aid only; not a guarantee of NAV movement.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search fund…" className="w-48 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-xs outline-none"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-xs outline-none"><option>ALL</option><option>STRONG BUY TODAY</option><option>BUY ON DIP</option><option>ACCUMULATE</option><option>WAIT</option><option>AVOID TODAY</option></select></div></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{funds.map(f=><article key={f.id} className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-medium text-white">{f.name}</h3><span className={`shrink-0 rounded-full border px-2 py-1 text-[9px] font-bold ${actionColor(f.actionTag)}`}>{f.actionTag}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><div className="text-lg font-semibold text-white">{f.finalDailyScore.toFixed(0)}</div><div className="text-[9px] text-slate-600">SCORE</div></div><div><div className="text-lg font-semibold text-white">{f.strategicScore.toFixed(0)}</div><div className="text-[9px] text-slate-600">TREND</div></div><div><div className="text-lg font-semibold text-white">{f.navOpportunityScore.toFixed(0)}</div><div className="text-[9px] text-slate-600">OPP.</div></div></div><p className="mt-4 text-xs leading-5 text-slate-500">{f.reason}</p></article>)}</div></section>
  <footer className="py-6 text-center text-[10px] text-slate-600">NSE index feed + AMFI/MFAPI NAV history · No database · Auto-refresh every 15 minutes</footer>
 </div></main>;
}
